name: Deploy static content to GitHub Pages

on:
  # Runs when changes are pushed to main
  push:
    branches: ['main']

  # Allows you to run workflow manually from Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy: # Single deploy job
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Set up Node
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 24
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
